In [1]:
#Import Pandas & read CSV files, setting to varibles
import pandas as pd
albums_file = "./data/spotify_albums.csv"
artists_file = "./data/spotify_artists.csv"
tracks_file = "./data/spotify_tracks.csv"
albums = pd.read_csv(albums_file, header=0)
artists = pd.read_csv(artists_file, header=0)
tracks = pd.read_csv(tracks_file, header=0)

In [19]:
#### head(), tail(), and .shape ####

# The head() function is used to displays the top n rows of a dataframe. n being the parameter fo the function, default being 5.
# The tail() function is the inverse of the head() function. It displays the bottom n rows of a dataframe The default is still 5.
# the .shape is used to return the dimensions of our data sets in a tuple (rows, columns)

## The output here tells us that this dataset is indeed about spotify albums. It has unique IDs for the artists and links to the album, suggesting that this dataset is used by the spotify app and used to return things to the user. Beyond that we can also see that it includes album types, track numbers, name, release date, and IDs to be read by (assuming) the app. 
albums.head()
## The output is telling us the same information here, with this though we can see that this data frame is 75510 rows. We also spot a new input for release_date_precision, instead of day we can now see year inputted.
albums.tail(10)
## Output here is pretty simple. rows = 75511 columns = 16
albums.shape

## With the output on the artists file we can see popularity rankings, follower count, genres, unique ID, name of the artist, track ID and the type of data (artist)
artists.head()
## Output for artists file here is again is the exact same data type, but we can now see the end of dataset. Which is 56128 rows.
artists.tail(9)
## again, rows = 56129 columns = 9
artists.shape

## The output for the tracks file is showing us specific songs along with properties of those tracks like: acousticness, countries the song can be accessed in, country of origin, danceability, duration, speechiness, tempo, time signature, track number in the album, and the valence.
## something to note here is that our energy,href,id,instrumentalness,key,liveness,loudness,lyrics,mode,name,playlist,popularity, which can be seen from the csv file are not displayed here for brevity sake.
tracks.head()
## Again here same data is available, but sommething to note is that we are still not getting all of our columns displayed at this time. We can see that there's 101,938 rows in this dataset.
tracks.tail(10)
## returns rows = 101939 columns = 32
tracks.shape

(101939, 32)

In [20]:
#For Albums, use .loc to show just rows 10-20 of the 'name' and 'release_date' columns
albums.loc[10:20, ['name', 'release_date']]

                                                 name release_date
10  Beethoven: 6 Bagatelles & Piano Sonatas Nos. 3...   2019-03-01
11                                Au Long de la Loire   2019-03-01
12                                     I Still Miss U   2019-03-15
13                                     Kolmekymppinen         1980
14                                              Bruja   2018-04-24
15                            Sonatas for two violins   2019-03-01
16                                            Sirènes   2019-03-01
17                                       Light of Day   2019-03-01
18                                   Madame del Campo   2015-08-03
19  Beethoven: Piano Concerto No. 2 & Triple Conce...   2019-03-01
20                                      Violinsonaten   2019-03-01

In [97]:
#Remove duplicates from each dataset
albums_dupdrop = albums.drop_duplicates()
artists_dupdrop = artists.drop_duplicates()
tracks_dupdrop = tracks.drop_duplicates()
print(albums.shape)
print(albums_dupdrop.shape)
print(artists.shape)
print(artists_dupdrop.shape)
print(tracks.shape)
print(tracks_dupdrop.shape)

(75511, 16)
(75511, 16)
(56129, 9)
(56129, 9)
(101939, 31)
(101939, 31)

In [38]:
    #For Artists: Write a map() function to replace the empty list ([]) entries in the genres column with NaNs
    #(but don't alter the list entries in genres that contain values!)
def empty_field_destroyer(value):
    if value == '[]':
        return float()
    else:
        return value
artists["genres"] = artists["genres"].map(empty_field_destroyer)
artists.head(9)
# Im not sure if this is the best way to get a NaN, but everything else i've tried returns it as a string. Which isn't a true NaN floating point object.
# I considered using numpy, which has a way to produce a NaN object with numpy.nan. But we haven't covered that so I left it as is!

,Unnamed: 0,artist_popularity,followers,genres,id,name,track_id,track_name_prev,type
0,0,44,23230,"['sertanejo', 'sertanejo pop', 'sertanejo trad...",4mGnpjhqgx4RUdsIJiURdo,Juliano Cezar,0wmDmAILuW9e2aRttkl4aC,track_9,artist
1,1,22,313,NaN,1dLnVku4VQUOLswwDFvRc9,The Grenadines,4wqwj0gA8qPZKLl5WVqXml,track_30,artist
2,2,26,1596,['danish pop rock'],6YVY310fjfUzKi8hiqR7iK,Gangway,1bFqWDbvHmZe2f4Nf9qaD8,track_38,artist
3,3,31,149,['uk alternative pop'],2VElyouiCfoYPDJluzwJwK,FADES,3MFSUBAidPzRBbIS7BDj1S,track_34,artist
4,4,21,11,['french baroque'],4agVy03qW8juSysCTUOuDI,Jean-Pierre Guignon,2r3q57FhxdsCyYr0kuDq4b,track_26,artist
5,5,43,81,NaN,38VBjthd0szbS6wpDMafrb,Filhos,453KeZU566kjNfs1IH4yHU,track_15,artist
6,6,34,8358,NaN,36mHwYa65L0WZbAXY2iSGw,Eloq,6hC5Tl0S5aQCw646JuN91w,track_43,artist
7,7,7,158,NaN,1jJyy00XfxjB4tMAv5OT0q,Fravær,5005eeCJ9KTFAAzh2NC9mr,track_48,artist
8,8,21,30,NaN,10A8WbBJ0zW8MnvTsUL6os,Camille Pépin,56fBsCXwpBnxe4JkF66gyF,track_73,artist

In [47]:
# For Tracks:
    #Print the names of the columns in Tracks
def print_track_cols(col):
    for col in tracks.columns:
        print(col)
print_track_cols(tracks)
    # First, look at the values for lyrics to see why you think they don't parse well in Excel and some other programs
print(tracks.lyrics)
    # Drop the lyrics column
tracks.drop("lyrics", axis=1, inplace=True)
    # Target tracks file, drop the following: "lyrics" column, use the axis of columns, and do it inplace(modifying the dataframe permanently)
    # Print the names of the Tracks columns again, to show that the 'lyrics' column has been dropped
print_track_cols(tracks)

,Unnamed: 0,acousticness,album_id,analysis_url,artists_id,available_markets,country,danceability,disc_number,duration_ms,...,preview_url,speechiness,tempo,time_signature,track_href,track_name_prev,track_number,uri,valence,type
0,0,0.294,0D3QufeCudpQANOR7luqdr,https://api.spotify.com/v1/audio-analysis/5qlj...,['3mxJuHRn2ZWD5OofvJtDZY'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.698,1.0,235584.0,...,https://p.scdn.co/mp3-preview/1b05a902da3a251d...,0.0262,115.018,4.0,https://api.spotify.com/v1/tracks/5qljLQuKnNJf...,track_14,1.0,spotify:track:5qljLQuKnNJf4F4vfxQB0V,0.622,track
1,1,0.863,1bcqsH5UyTBzmh9YizdsBE,https://api.spotify.com/v1/audio-analysis/3VAX...,['4xWMewm6CYMstu0sPgd9jJ'],"['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...",BE,0.719,1.0,656960.0,...,https://p.scdn.co/mp3-preview/d8140736a6131cb5...,0.9220,115.075,3.0,https://api.spotify.com/v1/tracks/3VAX2MJdmdqA...,track_3,3.0,spotify:track:3VAX2MJdmdqARLSU5hPMpm,0.589,track
2,2,0.750,4tKijjmxGClg4JOLAyo2qE,https://api.spotify.com/v1/audio-analysis/1L3Y...,['3hYaK5FF3YAglCj5HZgBnP'],['GB'],BE,0.466,1.0,492840.0,...,https://p.scdn.co/mp3-preview/c8af28fb15185b18...,0.9440,79.565,4.0,https://api.spotify.com/v1/tracks/1L3YAhsEMrGV...,track_4,4.0,spotify:track:1L3YAhsEMrGVvCgDXj2TYn,0.085,track

In [52]:
# Using Pandas, perform the following joins, choosing the join type that you think is appropriate.
# Make a comment in your code file on why you chose that join type

    # Join artists and albums on the artist ID
artists_albums = pd.merge(artists, albums, how='inner', left_on='id', right_on='artist_id')
    # I used the default inner join, I added it to the code to show that.
    # I did this because it retains the most amount of data and merging the shared value between the tables.
    # The other joins would produce a lot of empty fields, which clogs up our dataset.
# print the head() and shape of the resulting DataFrame
# print(artists_albums.head(), artists_albums.shape)
# Join albums and tracks on the album ID
albums_tracks = pd.merge(albums, tracks, left_on='id', right_on='album_id')
    # Another inner join, unless I know the use for this dataset I am going to leave as much data as possible.
# print the head() and shape of the resulting DataFrame
print(albums_tracks.head(), albums_tracks.shape)

   Unnamed: 0_x album_type               artist_id  \
0             0     single  3DiDSECUqqY1AuBP8qtaIa
1             1      album  6s1pCNXcbdtQJlsnM1hRIA
2             2     single  5YjfNaHq05WrwldRe1QSBc
3             3     single  2G9Vc16JCpnZmK4uGH46Fa
4             4     single  2dwM9OcE4c3Ph1UBINSodx

                                 available_markets_x  \
0  ['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...
1  ['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...
2  ['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...
3  ['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...
4  ['AD', 'AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BH...

                                       external_urls  \
0  {'spotify': 'https://open.spotify.com/album/1g...
1  {'spotify': 'https://open.spotify.com/album/4K...
2  {'spotify': 'https://open.spotify.com/album/7n...
3  {'spotify': 'https://open.spotify.com/album/6p...
4  {'spotify': 'https://open.spotify.com/album/1X...

                                              href_x                    id_x  \
0  https://api.spotify.com/v1/albums/1gAM7M4rBwEb...  1gAM7M4rBwEbSPeAQR2nx1
1  https://api.spotify.com/v1/albums/4KfJZV7WfolY...  4KfJZV7WfolYlxBzOTo66s
2  https://api.spotify.com/v1/albums/7nLYY7uAVUb5...  7nLYY7uAVUb57kpd7tZxnS
3  https://api.spotify.com/v1/albums/6p20Rt4x2Qn5...  6p20Rt4x2Qn5mUMRi1s6pj
4  https://api.spotify.com/v1/albums/1XeoOqC1q7U2...  1XeoOqC1q7U2iyLEQJ64cu

                                              images  \
0  [{'height': 640, 'url': 'https://i.scdn.co/ima...
1  [{'height': 640, 'url': 'https://i.scdn.co/ima...
2  [{'height': 640, 'url': 'https://i.scdn.co/ima...
3  [{'height': 640, 'url': 'https://i.scdn.co/ima...
4  [{'height': 640, 'url': 'https://i.scdn.co/ima...

                                              name_x release_date  ...  \
0                              If I Ain't Got You EP   2019-02-08  ...
1  Shostakovich Symphony No.5 - Four Romances on ...   2019-03-01  ...
2                                       Take My Bass   2019-03-14  ...
3                                Hypnotizing (Are U)   2016-11-16  ...
4                                           Sunshine   2018-07-20  ...

                                         preview_url  speechiness    tempo  \
0  https://p.scdn.co/mp3-preview/06b26d3394260b30...       0.1090  118.539
1  https://p.scdn.co/mp3-preview/76a758fad6bc2d66...       0.0522  133.458
2  https://p.scdn.co/mp3-preview/e2a872994fa74cc1...       0.0669  126.060
3  https://p.scdn.co/mp3-preview/619a85e30cc382a5...       0.0840  159.992
4  https://p.scdn.co/mp3-preview/592f778ca79064ed...       0.0592   89.655

  time_signature                                         track_href  \
0            3.0  https://api.spotify.com/v1/tracks/2iejTMy9XZ8G...
1            3.0  https://api.spotify.com/v1/tracks/1WQfghEjszJJ...
2            4.0  https://api.spotify.com/v1/tracks/3jJKj4QTK3v1...
3            4.0  https://api.spotify.com/v1/tracks/1xGtDafUZbHy...
4            4.0  https://api.spotify.com/v1/tracks/0gWtsXvXOzAT...

  track_name_prev_y  track_number                                 uri_y  \
0          track_32           2.0  spotify:track:2iejTMy9XZ8Gaae0aQ2yl0
1          track_11           2.0  spotify:track:1WQfghEjszJJ4H8MAWrQ2C
2          track_15           1.0  spotify:track:3jJKj4QTK3v18ZSwpk7AcV
3          track_46           1.0  spotify:track:1xGtDafUZbHyYC3Xarcbrj
4          track_10           1.0  spotify:track:0gWtsXvXOzAT6FtM3ur8in

  valence type_y
0   0.197  track
1   0.413  track
2   0.448  track
3   0.429  track
4   0.505  track

[5 rows x 47 columns] (101939, 47)

In [79]:
# Use the Pandas to calculate some statistics on the data, and print the results:

#     Which artists appear the most times in the Artists data?
# display just artists column and then sort in descending order
artists_count = artists['name'].value_counts()
print(artists_count)
        # Sasha
# Which artists have the highest 'artist_popularity' rankings? (list the top ten in descending order)
artists_pop = artists['artist_popularity'].value_counts()
print(pd.DataFrame(artists['name'],artists_pop).head(10))
        # Jay Soto, The Winans, Johnathan Cohen, etc...(rest are displayed below for your viewing pleasure)

Haze                  5
Sasha                 5
Elias                 4
Karina                4
Alex                  4
                     ..
Steuerfreimoney       1
Avery Florence        1
Ian van Dahl          1
Bikini Kill           1
Something For Kate    1
Name: name, Length: 55505, dtype: int64
                                name
artist_popularity
1296                        Jay Soto
1249                      The Winans
1245                  Jonathan Cohen
1238                    Carlo Farina
1234                            Sobs
1206                   Jair Oliveira
1199                    Jason Reeves
1198               Marta Aznavoorian
1192                           Owain
1185                     Vilde Frang

In [127]:
from datetime import datetime
# Bonus Point: How many albums came out in each year? (Notice that the values in the release_date column of Albums is in the format yyyy-mm-dd)
albums['release_date'] = pd.to_datetime(albums['release_date'])
years = albums['release_date'].dt.year
year_count = years.value_counts()
print(year_count)

2018    22050
2019    11125
2017     9231
2016     5111
2015     3229
        ...
1926        1
1948        1
1942        1
1944        1
1923        1
Name: release_date, Length: 88, dtype: int64